{"id":"apierror","metadata":{"name":"ApiError","description":"<h1 id=\"apierror\">ApiError</h1>\n\n<p>Raised when an API call is not successful.</p>","source":"lib/gcloud/storage/errors.rb#L31","resources":[],"examples":[]},"methods":[{"metadata":{"name":"code","description":"<p>The code of the error.</p>","source":"lib/gcloud/storage/errors.rb#L34","resources":[],"examples":[]},"params":[],"exceptions":[],"returns":[]},{"metadata":{"name":"errors","description":"<p>The errors encountered.</p>","source":"lib/gcloud/storage/errors.rb#L38","resources":[],"examples":[]},"params":[],"exceptions":[],"returns":[]},{"metadata":{"name":"initialize","description":"","source":"lib/gcloud/storage/errors.rb#L40","resources":[],"examples":[]},"params":[],"exceptions":[],"returns":[{"types":["ApiError"],"description":"a new instance of ApiError"}]}]}